<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_get_contents.proto

namespace Proto\FileGetContentsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>proto.FileGetContentsResponse.FileContents</code>
 */
class FileContents extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * A file identifier.
     * <p>
     * This SHALL be the identifier of a file that exists in HFS.<br/>
     * This value SHALL identify the file that was queried.
     *
     * Generated from protobuf field <code>.proto.FileID fileID = 1;</code>
     */
    protected $fileID = null;
    /**
     **
     * A byte array of file content.
     * <p>
     * This SHALL contain the full content of the requested file.<br/>
     * This SHALL be empty if, and only if, the file content is empty.
     *
     * Generated from protobuf field <code>bytes contents = 2;</code>
     */
    protected $contents = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\FileID $fileID
     *          *
     *           A file identifier.
     *           <p>
     *           This SHALL be the identifier of a file that exists in HFS.<br/>
     *           This value SHALL identify the file that was queried.
     *     @type string $contents
     *          *
     *           A byte array of file content.
     *           <p>
     *           This SHALL contain the full content of the requested file.<br/>
     *           This SHALL be empty if, and only if, the file content is empty.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FileGetContents::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * A file identifier.
     * <p>
     * This SHALL be the identifier of a file that exists in HFS.<br/>
     * This value SHALL identify the file that was queried.
     *
     * Generated from protobuf field <code>.proto.FileID fileID = 1;</code>
     * @return \Proto\FileID|null
     */
    public function getFileID()
    {
        return $this->fileID;
    }

    public function hasFileID()
    {
        return isset($this->fileID);
    }

    public function clearFileID()
    {
        unset($this->fileID);
    }

    /**
     **
     * A file identifier.
     * <p>
     * This SHALL be the identifier of a file that exists in HFS.<br/>
     * This value SHALL identify the file that was queried.
     *
     * Generated from protobuf field <code>.proto.FileID fileID = 1;</code>
     * @param \Proto\FileID $var
     * @return $this
     */
    public function setFileID($var)
    {
        GPBUtil::checkMessage($var, \Proto\FileID::class);
        $this->fileID = $var;

        return $this;
    }

    /**
     **
     * A byte array of file content.
     * <p>
     * This SHALL contain the full content of the requested file.<br/>
     * This SHALL be empty if, and only if, the file content is empty.
     *
     * Generated from protobuf field <code>bytes contents = 2;</code>
     * @return string
     */
    public function getContents()
    {
        return $this->contents;
    }

    /**
     **
     * A byte array of file content.
     * <p>
     * This SHALL contain the full content of the requested file.<br/>
     * This SHALL be empty if, and only if, the file content is empty.
     *
     * Generated from protobuf field <code>bytes contents = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContents($var)
    {
        GPBUtil::checkString($var, False);
        $this->contents = $var;

        return $this;
    }

}

