<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state/hints/hints_types.proto

namespace Com\Hedera\Hapi\Node\State\Hints;

use UnexpectedValueException;

/**
 **
 * The stage of a CRS construction.
 *
 * Protobuf type <code>com.hedera.hapi.node.state.hints.CRSStage</code>
 */
class CRSStage
{
    /**
     **
     * The network is gathering contributions to the CRS from all nodes.
     *
     * Generated from protobuf enum <code>GATHERING_CONTRIBUTIONS = 0;</code>
     */
    const GATHERING_CONTRIBUTIONS = 0;
    /**
     **
     * The network is waiting for some grace period to allow the verification future
     * to be completed after the last node has contributed to the CRS.
     *
     * Generated from protobuf enum <code>WAITING_FOR_ADOPTING_FINAL_CRS = 1;</code>
     */
    const WAITING_FOR_ADOPTING_FINAL_CRS = 1;
    /**
     **
     * The network has completed the CRS construction and is set in the CrsState.
     *
     * Generated from protobuf enum <code>COMPLETED = 2;</code>
     */
    const COMPLETED = 2;

    private static $valueToName = [
        self::GATHERING_CONTRIBUTIONS => 'GATHERING_CONTRIBUTIONS',
        self::WAITING_FOR_ADOPTING_FINAL_CRS => 'WAITING_FOR_ADOPTING_FINAL_CRS',
        self::COMPLETED => 'COMPLETED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

