<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state/hints/hints_types.proto

namespace Com\Hedera\Hapi\Node\State\Hints;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * A node's vote for the consensus output of a hinTS preprocessing
 * algorithm.
 *
 * Generated from protobuf message <code>com.hedera.hapi.node.state.hints.PreprocessingVote</code>
 */
class PreprocessingVote extends \Google\Protobuf\Internal\Message
{
    protected $vote;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Com\Hedera\Hapi\Node\State\Hints\PreprocessedKeys $preprocessed_keys
     *          *
     *           The preprocessed keys this node is voting for.
     *     @type int|string $congruent_node_id
     *          *
     *           The id of any node that already voted for the exact keys
     *           that this node wanted to vote for.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\State\Hints\HintsTypes::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * The preprocessed keys this node is voting for.
     *
     * Generated from protobuf field <code>.com.hedera.hapi.node.state.hints.PreprocessedKeys preprocessed_keys = 1;</code>
     * @return \Com\Hedera\Hapi\Node\State\Hints\PreprocessedKeys|null
     */
    public function getPreprocessedKeys()
    {
        return $this->readOneof(1);
    }

    public function hasPreprocessedKeys()
    {
        return $this->hasOneof(1);
    }

    /**
     **
     * The preprocessed keys this node is voting for.
     *
     * Generated from protobuf field <code>.com.hedera.hapi.node.state.hints.PreprocessedKeys preprocessed_keys = 1;</code>
     * @param \Com\Hedera\Hapi\Node\State\Hints\PreprocessedKeys $var
     * @return $this
     */
    public function setPreprocessedKeys($var)
    {
        GPBUtil::checkMessage($var, \Com\Hedera\Hapi\Node\State\Hints\PreprocessedKeys::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     **
     * The id of any node that already voted for the exact keys
     * that this node wanted to vote for.
     *
     * Generated from protobuf field <code>uint64 congruent_node_id = 2;</code>
     * @return int|string
     */
    public function getCongruentNodeId()
    {
        return $this->readOneof(2);
    }

    public function hasCongruentNodeId()
    {
        return $this->hasOneof(2);
    }

    /**
     **
     * The id of any node that already voted for the exact keys
     * that this node wanted to vote for.
     *
     * Generated from protobuf field <code>uint64 congruent_node_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCongruentNodeId($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getVote()
    {
        return $this->whichOneof("vote");
    }

}

