<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * A transaction body for handling a set of transactions atomically.
 *
 * Generated from protobuf message <code>proto.AtomicBatchTransactionBody</code>
 */
class AtomicBatchTransactionBody extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * A list of signed bytes that represent the batch transactions.
     *
     * Generated from protobuf field <code>repeated bytes transactions = 1;</code>
     */
    private $transactions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $transactions
     *          *
     *           A list of signed bytes that represent the batch transactions.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * A list of signed bytes that represent the batch transactions.
     *
     * Generated from protobuf field <code>repeated bytes transactions = 1;</code>
     * @return RepeatedField<string>
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     **
     * A list of signed bytes that represent the batch transactions.
     *
     * Generated from protobuf field <code>repeated bytes transactions = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->transactions = $arr;

        return $this;
    }

}

