<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_get_contents.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * A response to a query for the content of a file in the
 * Hedera File Service (HFS).
 * This message SHALL contain the full content of the requested file, but
 * SHALL NOT contain any metadata.
 *
 * Generated from protobuf message <code>proto.FileGetContentsResponse</code>
 */
class FileGetContentsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * The standard response information for queries.<br/>
     * This includes the values requested in the `QueryHeader`
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     **
     * A combination of File identifier and content bytes.
     * <p>
     * This SHALL NOT be set if the file does not exist.<br/>
     * The network MAY generate a state proof for this field.
     *
     * Generated from protobuf field <code>.proto.FileGetContentsResponse.FileContents fileContents = 2;</code>
     */
    protected $fileContents = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\ResponseHeader $header
     *          *
     *           The standard response information for queries.<br/>
     *           This includes the values requested in the `QueryHeader`
     *           (cost, state proof, both, or neither).
     *     @type \Proto\FileGetContentsResponse\FileContents $fileContents
     *          *
     *           A combination of File identifier and content bytes.
     *           <p>
     *           This SHALL NOT be set if the file does not exist.<br/>
     *           The network MAY generate a state proof for this field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FileGetContents::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * The standard response information for queries.<br/>
     * This includes the values requested in the `QueryHeader`
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.ResponseHeader header = 1;</code>
     * @return \Proto\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     **
     * The standard response information for queries.<br/>
     * This includes the values requested in the `QueryHeader`
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.ResponseHeader header = 1;</code>
     * @param \Proto\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Proto\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     **
     * A combination of File identifier and content bytes.
     * <p>
     * This SHALL NOT be set if the file does not exist.<br/>
     * The network MAY generate a state proof for this field.
     *
     * Generated from protobuf field <code>.proto.FileGetContentsResponse.FileContents fileContents = 2;</code>
     * @return \Proto\FileGetContentsResponse\FileContents|null
     */
    public function getFileContents()
    {
        return $this->fileContents;
    }

    public function hasFileContents()
    {
        return isset($this->fileContents);
    }

    public function clearFileContents()
    {
        unset($this->fileContents);
    }

    /**
     **
     * A combination of File identifier and content bytes.
     * <p>
     * This SHALL NOT be set if the file does not exist.<br/>
     * The network MAY generate a state proof for this field.
     *
     * Generated from protobuf field <code>.proto.FileGetContentsResponse.FileContents fileContents = 2;</code>
     * @param \Proto\FileGetContentsResponse\FileContents $var
     * @return $this
     */
    public function setFileContents($var)
    {
        GPBUtil::checkMessage($var, \Proto\FileGetContentsResponse\FileContents::class);
        $this->fileContents = $var;

        return $this;
    }

}

