<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: network_get_execution_time.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * A response to a `networkGetExecutionTime` query.
 *
 * @deprecated
 * Generated from protobuf message <code>proto.NetworkGetExecutionTimeResponse</code>
 */
class NetworkGetExecutionTimeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * The standard response information for queries.<br/>
     * This includes the values requested in the `QueryHeader`
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     **
     * A list of execution times, in nanoseconds.
     * <p>
     * This list SHALL be in the same order as the transaction
     * identifiers were presented in the query.
     *
     * Generated from protobuf field <code>repeated uint64 execution_times = 2;</code>
     */
    private $execution_times;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\ResponseHeader $header
     *          *
     *           The standard response information for queries.<br/>
     *           This includes the values requested in the `QueryHeader`
     *           (cost, state proof, both, or neither).
     *     @type int[]|string[] $execution_times
     *          *
     *           A list of execution times, in nanoseconds.
     *           <p>
     *           This list SHALL be in the same order as the transaction
     *           identifiers were presented in the query.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\NetworkGetExecutionTime::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * The standard response information for queries.<br/>
     * This includes the values requested in the `QueryHeader`
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.ResponseHeader header = 1;</code>
     * @return \Proto\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     **
     * The standard response information for queries.<br/>
     * This includes the values requested in the `QueryHeader`
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.ResponseHeader header = 1;</code>
     * @param \Proto\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Proto\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     **
     * A list of execution times, in nanoseconds.
     * <p>
     * This list SHALL be in the same order as the transaction
     * identifiers were presented in the query.
     *
     * Generated from protobuf field <code>repeated uint64 execution_times = 2;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getExecutionTimes()
    {
        return $this->execution_times;
    }

    /**
     **
     * A list of execution times, in nanoseconds.
     * <p>
     * This list SHALL be in the same order as the transaction
     * identifiers were presented in the query.
     *
     * Generated from protobuf field <code>repeated uint64 execution_times = 2;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setExecutionTimes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->execution_times = $arr;

        return $this;
    }

}

