<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crypto_get_stakers.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * information about a single account that is proxy staking
 *
 * @deprecated
 * Generated from protobuf message <code>proto.ProxyStaker</code>
 */
class ProxyStaker extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * The Account ID that is proxy staking
     *
     * Generated from protobuf field <code>.proto.AccountID accountID = 1;</code>
     */
    protected $accountID = null;
    /**
     **
     * The number of hbars that are currently proxy staked
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     */
    protected $amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\AccountID $accountID
     *          *
     *           The Account ID that is proxy staking
     *     @type int|string $amount
     *          *
     *           The number of hbars that are currently proxy staked
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CryptoGetStakers::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * The Account ID that is proxy staking
     *
     * Generated from protobuf field <code>.proto.AccountID accountID = 1;</code>
     * @return \Proto\AccountID|null
     */
    public function getAccountID()
    {
        return $this->accountID;
    }

    public function hasAccountID()
    {
        return isset($this->accountID);
    }

    public function clearAccountID()
    {
        unset($this->accountID);
    }

    /**
     **
     * The Account ID that is proxy staking
     *
     * Generated from protobuf field <code>.proto.AccountID accountID = 1;</code>
     * @param \Proto\AccountID $var
     * @return $this
     */
    public function setAccountID($var)
    {
        GPBUtil::checkMessage($var, \Proto\AccountID::class);
        $this->accountID = $var;

        return $this;
    }

    /**
     **
     * The number of hbars that are currently proxy staked
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     **
     * The number of hbars that are currently proxy staked
     *
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

}

