<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: response.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * A single query response.
 * Each query MUST define its specific response type.<br/>
 * Each query response MUST include both the information request and a
 * `ResponseHeader`.<br/>
 * All possible query response types MUST be listed here in a `oneof`.
 *
 * Generated from protobuf message <code>proto.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    protected $response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\GetByKeyResponse $getByKey
     *          *
     *           A response for a query requesting all accounts, claims, files, and
     *           smart contract instances whose associated keys include the given Key.
     *           <p>
     *           > This query is no longer supported.
     *     @type \Proto\GetBySolidityIDResponse $getBySolidityID
     *          *
     *           A response for a query requesting Contract, Account, and File
     *           identifiers for a smart contract, given a Solidity identifier.
     *     @type \Proto\ContractCallLocalResponse $contractCallLocal
     *          *
     *           A response for a _local_ call to a query function of a given smart
     *           contract, providing function parameter inputs as needed.
     *           <p>
     *           > This call is only performed on the local node. It is _not_ a
     *           > network consensus result.
     *     @type \Proto\ContractGetBytecodeResponse $contractGetBytecodeResponse
     *          *
     *           A response for a query requesting the current bytecode for
     *           a smart contract.
     *     @type \Proto\ContractGetInfoResponse $contractGetInfo
     *          *
     *           A response for a query requesting detailed information about
     *           a smart contract.
     *     @type \Proto\ContractGetRecordsResponse $contractGetRecordsResponse
     *          *
     *           A response for a query requesting records of all transactions
     *           against the given contract in the last 25 hours.
     *           <p>
     *           > This query is no longer supported.
     *     @type \Proto\CryptoGetAccountBalanceResponse $cryptogetAccountBalance
     *          *
     *           A response for a query requesting the HBAR balance of an account
     *           or contract.
     *     @type \Proto\CryptoGetAccountRecordsResponse $cryptoGetAccountRecords
     *          *
     *           A response for a query requesting records of all "recent"
     *           transactions for which the specified account is the effective payer.
     *     @type \Proto\CryptoGetInfoResponse $cryptoGetInfo
     *          *
     *           A response for a query requesting information for an account.<br/>
     *           This query includes balance, but not allowances or token
     *           relationships.
     *     @type \Proto\CryptoGetLiveHashResponse $cryptoGetLiveHash
     *          *
     *           A response for a query requesting detail for a specific live hash
     *           associated to a specific account.
     *           <p>
     *           > This query is no longer supported.
     *     @type \Proto\CryptoGetStakersResponse $cryptoGetProxyStakers
     *          *
     *           A response for a query requesting all the accounts that are proxy
     *           staking to this account.
     *           <p>
     *           > This query is no longer supported.
     *     @type \Proto\FileGetContentsResponse $fileGetContents
     *          *
     *           A response for a query requesting the content of a file in the
     *           Hedera File Service (HFS).
     *     @type \Proto\FileGetInfoResponse $fileGetInfo
     *          *
     *           A response for a query requesting file metadata from the
     *           Hedera File Service (HFS).
     *     @type \Proto\TransactionGetReceiptResponse $transactionGetReceipt
     *          *
     *           A response for a query requesting the post-consensus (final)
     *           result of a transaction.
     *     @type \Proto\TransactionGetRecordResponse $transactionGetRecord
     *          *
     *           A response for a query requesting a transaction record; the detail
     *           changes completed in response to a transaction.
     *     @type \Proto\TransactionGetFastRecordResponse $transactionGetFastRecord
     *          *
     *           A response for a query requesting a very recent transaction record.
     *           <p>
     *           > This query is no longer supported.
     *     @type \Proto\ConsensusGetTopicInfoResponse $consensusGetTopicInfo
     *          *
     *           A response for a query requesting the current state of a topic for
     *           the Hedera Consensus Service (HCS).
     *     @type \Proto\NetworkGetVersionInfoResponse $networkGetVersionInfo
     *          *
     *           A response for a query requesting the deployed versions of Hedera
     *           Services and the API definitions in semantic version format
     *     @type \Proto\TokenGetInfoResponse $tokenGetInfo
     *          *
     *           A response for a query requesting metadata for a specific Token.
     *     @type \Proto\ScheduleGetInfoResponse $scheduleGetInfo
     *          *
     *           A response for a query requesting detail for a scheduled transaction.
     *     @type \Proto\TokenGetAccountNftInfosResponse $tokenGetAccountNftInfos
     *          *
     *           A response for a query requesting detail for a subset of individual
     *           non-fungible/unique tokens owned by an account.<br/>
     *           The requested tokens are selected by a list index, which is based
     *           on the order in which the tokens were added to the account.
     *     @type \Proto\TokenGetNftInfoResponse $tokenGetNftInfo
     *          *
     *           A response for a query requesting detail for a specific
     *           non-fungible/unique token selected by both token identifier and
     *           serial number.
     *     @type \Proto\TokenGetNftInfosResponse $tokenGetNftInfos
     *          *
     *           A response for a query requesting detail for a subset of individual
     *           non-fungible/unique tokens.<br/>
     *           The requested tokens are selected by a list index, which is based
     *           on the order in which the tokens were minted.
     *     @type \Proto\NetworkGetExecutionTimeResponse $networkGetExecutionTime
     *          *
     *           A response for a query requesting the time, in nanoseconds, spent
     *           in direct processing for one or more recent transactions.
     *           <p>
     *           > This query is no longer supported.
     *     @type \Proto\GetAccountDetailsResponse $accountDetails
     *          *
     *           A response for a query requesting detail information
     *           about an account.
     *           <p>
     *           This query is a privileged query and "system" account authorization
     *           is REQUIRED for this query.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * A response for a query requesting all accounts, claims, files, and
     * smart contract instances whose associated keys include the given Key.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.GetByKeyResponse getByKey = 1;</code>
     * @return \Proto\GetByKeyResponse|null
     */
    public function getGetByKey()
    {
        return $this->readOneof(1);
    }

    public function hasGetByKey()
    {
        return $this->hasOneof(1);
    }

    /**
     **
     * A response for a query requesting all accounts, claims, files, and
     * smart contract instances whose associated keys include the given Key.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.GetByKeyResponse getByKey = 1;</code>
     * @param \Proto\GetByKeyResponse $var
     * @return $this
     */
    public function setGetByKey($var)
    {
        GPBUtil::checkMessage($var, \Proto\GetByKeyResponse::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting Contract, Account, and File
     * identifiers for a smart contract, given a Solidity identifier.
     *
     * Generated from protobuf field <code>.proto.GetBySolidityIDResponse getBySolidityID = 2;</code>
     * @return \Proto\GetBySolidityIDResponse|null
     */
    public function getGetBySolidityID()
    {
        return $this->readOneof(2);
    }

    public function hasGetBySolidityID()
    {
        return $this->hasOneof(2);
    }

    /**
     **
     * A response for a query requesting Contract, Account, and File
     * identifiers for a smart contract, given a Solidity identifier.
     *
     * Generated from protobuf field <code>.proto.GetBySolidityIDResponse getBySolidityID = 2;</code>
     * @param \Proto\GetBySolidityIDResponse $var
     * @return $this
     */
    public function setGetBySolidityID($var)
    {
        GPBUtil::checkMessage($var, \Proto\GetBySolidityIDResponse::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     **
     * A response for a _local_ call to a query function of a given smart
     * contract, providing function parameter inputs as needed.
     * <p>
     * > This call is only performed on the local node. It is _not_ a
     * > network consensus result.
     *
     * Generated from protobuf field <code>.proto.ContractCallLocalResponse contractCallLocal = 3;</code>
     * @return \Proto\ContractCallLocalResponse|null
     */
    public function getContractCallLocal()
    {
        return $this->readOneof(3);
    }

    public function hasContractCallLocal()
    {
        return $this->hasOneof(3);
    }

    /**
     **
     * A response for a _local_ call to a query function of a given smart
     * contract, providing function parameter inputs as needed.
     * <p>
     * > This call is only performed on the local node. It is _not_ a
     * > network consensus result.
     *
     * Generated from protobuf field <code>.proto.ContractCallLocalResponse contractCallLocal = 3;</code>
     * @param \Proto\ContractCallLocalResponse $var
     * @return $this
     */
    public function setContractCallLocal($var)
    {
        GPBUtil::checkMessage($var, \Proto\ContractCallLocalResponse::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting the current bytecode for
     * a smart contract.
     *
     * Generated from protobuf field <code>.proto.ContractGetBytecodeResponse contractGetBytecodeResponse = 5;</code>
     * @return \Proto\ContractGetBytecodeResponse|null
     */
    public function getContractGetBytecodeResponse()
    {
        return $this->readOneof(5);
    }

    public function hasContractGetBytecodeResponse()
    {
        return $this->hasOneof(5);
    }

    /**
     **
     * A response for a query requesting the current bytecode for
     * a smart contract.
     *
     * Generated from protobuf field <code>.proto.ContractGetBytecodeResponse contractGetBytecodeResponse = 5;</code>
     * @param \Proto\ContractGetBytecodeResponse $var
     * @return $this
     */
    public function setContractGetBytecodeResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\ContractGetBytecodeResponse::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting detailed information about
     * a smart contract.
     *
     * Generated from protobuf field <code>.proto.ContractGetInfoResponse contractGetInfo = 4;</code>
     * @return \Proto\ContractGetInfoResponse|null
     */
    public function getContractGetInfo()
    {
        return $this->readOneof(4);
    }

    public function hasContractGetInfo()
    {
        return $this->hasOneof(4);
    }

    /**
     **
     * A response for a query requesting detailed information about
     * a smart contract.
     *
     * Generated from protobuf field <code>.proto.ContractGetInfoResponse contractGetInfo = 4;</code>
     * @param \Proto\ContractGetInfoResponse $var
     * @return $this
     */
    public function setContractGetInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\ContractGetInfoResponse::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting records of all transactions
     * against the given contract in the last 25 hours.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.ContractGetRecordsResponse contractGetRecordsResponse = 6;</code>
     * @return \Proto\ContractGetRecordsResponse|null
     */
    public function getContractGetRecordsResponse()
    {
        return $this->readOneof(6);
    }

    public function hasContractGetRecordsResponse()
    {
        return $this->hasOneof(6);
    }

    /**
     **
     * A response for a query requesting records of all transactions
     * against the given contract in the last 25 hours.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.ContractGetRecordsResponse contractGetRecordsResponse = 6;</code>
     * @param \Proto\ContractGetRecordsResponse $var
     * @return $this
     */
    public function setContractGetRecordsResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\ContractGetRecordsResponse::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting the HBAR balance of an account
     * or contract.
     *
     * Generated from protobuf field <code>.proto.CryptoGetAccountBalanceResponse cryptogetAccountBalance = 7;</code>
     * @return \Proto\CryptoGetAccountBalanceResponse|null
     */
    public function getCryptogetAccountBalance()
    {
        return $this->readOneof(7);
    }

    public function hasCryptogetAccountBalance()
    {
        return $this->hasOneof(7);
    }

    /**
     **
     * A response for a query requesting the HBAR balance of an account
     * or contract.
     *
     * Generated from protobuf field <code>.proto.CryptoGetAccountBalanceResponse cryptogetAccountBalance = 7;</code>
     * @param \Proto\CryptoGetAccountBalanceResponse $var
     * @return $this
     */
    public function setCryptogetAccountBalance($var)
    {
        GPBUtil::checkMessage($var, \Proto\CryptoGetAccountBalanceResponse::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting records of all "recent"
     * transactions for which the specified account is the effective payer.
     *
     * Generated from protobuf field <code>.proto.CryptoGetAccountRecordsResponse cryptoGetAccountRecords = 8;</code>
     * @return \Proto\CryptoGetAccountRecordsResponse|null
     */
    public function getCryptoGetAccountRecords()
    {
        return $this->readOneof(8);
    }

    public function hasCryptoGetAccountRecords()
    {
        return $this->hasOneof(8);
    }

    /**
     **
     * A response for a query requesting records of all "recent"
     * transactions for which the specified account is the effective payer.
     *
     * Generated from protobuf field <code>.proto.CryptoGetAccountRecordsResponse cryptoGetAccountRecords = 8;</code>
     * @param \Proto\CryptoGetAccountRecordsResponse $var
     * @return $this
     */
    public function setCryptoGetAccountRecords($var)
    {
        GPBUtil::checkMessage($var, \Proto\CryptoGetAccountRecordsResponse::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting information for an account.<br/>
     * This query includes balance, but not allowances or token
     * relationships.
     *
     * Generated from protobuf field <code>.proto.CryptoGetInfoResponse cryptoGetInfo = 9;</code>
     * @return \Proto\CryptoGetInfoResponse|null
     */
    public function getCryptoGetInfo()
    {
        return $this->readOneof(9);
    }

    public function hasCryptoGetInfo()
    {
        return $this->hasOneof(9);
    }

    /**
     **
     * A response for a query requesting information for an account.<br/>
     * This query includes balance, but not allowances or token
     * relationships.
     *
     * Generated from protobuf field <code>.proto.CryptoGetInfoResponse cryptoGetInfo = 9;</code>
     * @param \Proto\CryptoGetInfoResponse $var
     * @return $this
     */
    public function setCryptoGetInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\CryptoGetInfoResponse::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting detail for a specific live hash
     * associated to a specific account.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.CryptoGetLiveHashResponse cryptoGetLiveHash = 10;</code>
     * @return \Proto\CryptoGetLiveHashResponse|null
     */
    public function getCryptoGetLiveHash()
    {
        return $this->readOneof(10);
    }

    public function hasCryptoGetLiveHash()
    {
        return $this->hasOneof(10);
    }

    /**
     **
     * A response for a query requesting detail for a specific live hash
     * associated to a specific account.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.CryptoGetLiveHashResponse cryptoGetLiveHash = 10;</code>
     * @param \Proto\CryptoGetLiveHashResponse $var
     * @return $this
     */
    public function setCryptoGetLiveHash($var)
    {
        GPBUtil::checkMessage($var, \Proto\CryptoGetLiveHashResponse::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting all the accounts that are proxy
     * staking to this account.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.CryptoGetStakersResponse cryptoGetProxyStakers = 11;</code>
     * @return \Proto\CryptoGetStakersResponse|null
     */
    public function getCryptoGetProxyStakers()
    {
        return $this->readOneof(11);
    }

    public function hasCryptoGetProxyStakers()
    {
        return $this->hasOneof(11);
    }

    /**
     **
     * A response for a query requesting all the accounts that are proxy
     * staking to this account.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.CryptoGetStakersResponse cryptoGetProxyStakers = 11;</code>
     * @param \Proto\CryptoGetStakersResponse $var
     * @return $this
     */
    public function setCryptoGetProxyStakers($var)
    {
        GPBUtil::checkMessage($var, \Proto\CryptoGetStakersResponse::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting the content of a file in the
     * Hedera File Service (HFS).
     *
     * Generated from protobuf field <code>.proto.FileGetContentsResponse fileGetContents = 12;</code>
     * @return \Proto\FileGetContentsResponse|null
     */
    public function getFileGetContents()
    {
        return $this->readOneof(12);
    }

    public function hasFileGetContents()
    {
        return $this->hasOneof(12);
    }

    /**
     **
     * A response for a query requesting the content of a file in the
     * Hedera File Service (HFS).
     *
     * Generated from protobuf field <code>.proto.FileGetContentsResponse fileGetContents = 12;</code>
     * @param \Proto\FileGetContentsResponse $var
     * @return $this
     */
    public function setFileGetContents($var)
    {
        GPBUtil::checkMessage($var, \Proto\FileGetContentsResponse::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting file metadata from the
     * Hedera File Service (HFS).
     *
     * Generated from protobuf field <code>.proto.FileGetInfoResponse fileGetInfo = 13;</code>
     * @return \Proto\FileGetInfoResponse|null
     */
    public function getFileGetInfo()
    {
        return $this->readOneof(13);
    }

    public function hasFileGetInfo()
    {
        return $this->hasOneof(13);
    }

    /**
     **
     * A response for a query requesting file metadata from the
     * Hedera File Service (HFS).
     *
     * Generated from protobuf field <code>.proto.FileGetInfoResponse fileGetInfo = 13;</code>
     * @param \Proto\FileGetInfoResponse $var
     * @return $this
     */
    public function setFileGetInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\FileGetInfoResponse::class);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting the post-consensus (final)
     * result of a transaction.
     *
     * Generated from protobuf field <code>.proto.TransactionGetReceiptResponse transactionGetReceipt = 14;</code>
     * @return \Proto\TransactionGetReceiptResponse|null
     */
    public function getTransactionGetReceipt()
    {
        return $this->readOneof(14);
    }

    public function hasTransactionGetReceipt()
    {
        return $this->hasOneof(14);
    }

    /**
     **
     * A response for a query requesting the post-consensus (final)
     * result of a transaction.
     *
     * Generated from protobuf field <code>.proto.TransactionGetReceiptResponse transactionGetReceipt = 14;</code>
     * @param \Proto\TransactionGetReceiptResponse $var
     * @return $this
     */
    public function setTransactionGetReceipt($var)
    {
        GPBUtil::checkMessage($var, \Proto\TransactionGetReceiptResponse::class);
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting a transaction record; the detail
     * changes completed in response to a transaction.
     *
     * Generated from protobuf field <code>.proto.TransactionGetRecordResponse transactionGetRecord = 15;</code>
     * @return \Proto\TransactionGetRecordResponse|null
     */
    public function getTransactionGetRecord()
    {
        return $this->readOneof(15);
    }

    public function hasTransactionGetRecord()
    {
        return $this->hasOneof(15);
    }

    /**
     **
     * A response for a query requesting a transaction record; the detail
     * changes completed in response to a transaction.
     *
     * Generated from protobuf field <code>.proto.TransactionGetRecordResponse transactionGetRecord = 15;</code>
     * @param \Proto\TransactionGetRecordResponse $var
     * @return $this
     */
    public function setTransactionGetRecord($var)
    {
        GPBUtil::checkMessage($var, \Proto\TransactionGetRecordResponse::class);
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting a very recent transaction record.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.TransactionGetFastRecordResponse transactionGetFastRecord = 16;</code>
     * @return \Proto\TransactionGetFastRecordResponse|null
     */
    public function getTransactionGetFastRecord()
    {
        return $this->readOneof(16);
    }

    public function hasTransactionGetFastRecord()
    {
        return $this->hasOneof(16);
    }

    /**
     **
     * A response for a query requesting a very recent transaction record.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.TransactionGetFastRecordResponse transactionGetFastRecord = 16;</code>
     * @param \Proto\TransactionGetFastRecordResponse $var
     * @return $this
     */
    public function setTransactionGetFastRecord($var)
    {
        GPBUtil::checkMessage($var, \Proto\TransactionGetFastRecordResponse::class);
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting the current state of a topic for
     * the Hedera Consensus Service (HCS).
     *
     * Generated from protobuf field <code>.proto.ConsensusGetTopicInfoResponse consensusGetTopicInfo = 150;</code>
     * @return \Proto\ConsensusGetTopicInfoResponse|null
     */
    public function getConsensusGetTopicInfo()
    {
        return $this->readOneof(150);
    }

    public function hasConsensusGetTopicInfo()
    {
        return $this->hasOneof(150);
    }

    /**
     **
     * A response for a query requesting the current state of a topic for
     * the Hedera Consensus Service (HCS).
     *
     * Generated from protobuf field <code>.proto.ConsensusGetTopicInfoResponse consensusGetTopicInfo = 150;</code>
     * @param \Proto\ConsensusGetTopicInfoResponse $var
     * @return $this
     */
    public function setConsensusGetTopicInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\ConsensusGetTopicInfoResponse::class);
        $this->writeOneof(150, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting the deployed versions of Hedera
     * Services and the API definitions in semantic version format
     *
     * Generated from protobuf field <code>.proto.NetworkGetVersionInfoResponse networkGetVersionInfo = 151;</code>
     * @return \Proto\NetworkGetVersionInfoResponse|null
     */
    public function getNetworkGetVersionInfo()
    {
        return $this->readOneof(151);
    }

    public function hasNetworkGetVersionInfo()
    {
        return $this->hasOneof(151);
    }

    /**
     **
     * A response for a query requesting the deployed versions of Hedera
     * Services and the API definitions in semantic version format
     *
     * Generated from protobuf field <code>.proto.NetworkGetVersionInfoResponse networkGetVersionInfo = 151;</code>
     * @param \Proto\NetworkGetVersionInfoResponse $var
     * @return $this
     */
    public function setNetworkGetVersionInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\NetworkGetVersionInfoResponse::class);
        $this->writeOneof(151, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting metadata for a specific Token.
     *
     * Generated from protobuf field <code>.proto.TokenGetInfoResponse tokenGetInfo = 152;</code>
     * @return \Proto\TokenGetInfoResponse|null
     */
    public function getTokenGetInfo()
    {
        return $this->readOneof(152);
    }

    public function hasTokenGetInfo()
    {
        return $this->hasOneof(152);
    }

    /**
     **
     * A response for a query requesting metadata for a specific Token.
     *
     * Generated from protobuf field <code>.proto.TokenGetInfoResponse tokenGetInfo = 152;</code>
     * @param \Proto\TokenGetInfoResponse $var
     * @return $this
     */
    public function setTokenGetInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\TokenGetInfoResponse::class);
        $this->writeOneof(152, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting detail for a scheduled transaction.
     *
     * Generated from protobuf field <code>.proto.ScheduleGetInfoResponse scheduleGetInfo = 153;</code>
     * @return \Proto\ScheduleGetInfoResponse|null
     */
    public function getScheduleGetInfo()
    {
        return $this->readOneof(153);
    }

    public function hasScheduleGetInfo()
    {
        return $this->hasOneof(153);
    }

    /**
     **
     * A response for a query requesting detail for a scheduled transaction.
     *
     * Generated from protobuf field <code>.proto.ScheduleGetInfoResponse scheduleGetInfo = 153;</code>
     * @param \Proto\ScheduleGetInfoResponse $var
     * @return $this
     */
    public function setScheduleGetInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\ScheduleGetInfoResponse::class);
        $this->writeOneof(153, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting detail for a subset of individual
     * non-fungible/unique tokens owned by an account.<br/>
     * The requested tokens are selected by a list index, which is based
     * on the order in which the tokens were added to the account.
     *
     * Generated from protobuf field <code>.proto.TokenGetAccountNftInfosResponse tokenGetAccountNftInfos = 154;</code>
     * @return \Proto\TokenGetAccountNftInfosResponse|null
     */
    public function getTokenGetAccountNftInfos()
    {
        return $this->readOneof(154);
    }

    public function hasTokenGetAccountNftInfos()
    {
        return $this->hasOneof(154);
    }

    /**
     **
     * A response for a query requesting detail for a subset of individual
     * non-fungible/unique tokens owned by an account.<br/>
     * The requested tokens are selected by a list index, which is based
     * on the order in which the tokens were added to the account.
     *
     * Generated from protobuf field <code>.proto.TokenGetAccountNftInfosResponse tokenGetAccountNftInfos = 154;</code>
     * @param \Proto\TokenGetAccountNftInfosResponse $var
     * @return $this
     */
    public function setTokenGetAccountNftInfos($var)
    {
        GPBUtil::checkMessage($var, \Proto\TokenGetAccountNftInfosResponse::class);
        $this->writeOneof(154, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting detail for a specific
     * non-fungible/unique token selected by both token identifier and
     * serial number.
     *
     * Generated from protobuf field <code>.proto.TokenGetNftInfoResponse tokenGetNftInfo = 155;</code>
     * @return \Proto\TokenGetNftInfoResponse|null
     */
    public function getTokenGetNftInfo()
    {
        return $this->readOneof(155);
    }

    public function hasTokenGetNftInfo()
    {
        return $this->hasOneof(155);
    }

    /**
     **
     * A response for a query requesting detail for a specific
     * non-fungible/unique token selected by both token identifier and
     * serial number.
     *
     * Generated from protobuf field <code>.proto.TokenGetNftInfoResponse tokenGetNftInfo = 155;</code>
     * @param \Proto\TokenGetNftInfoResponse $var
     * @return $this
     */
    public function setTokenGetNftInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\TokenGetNftInfoResponse::class);
        $this->writeOneof(155, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting detail for a subset of individual
     * non-fungible/unique tokens.<br/>
     * The requested tokens are selected by a list index, which is based
     * on the order in which the tokens were minted.
     *
     * Generated from protobuf field <code>.proto.TokenGetNftInfosResponse tokenGetNftInfos = 156;</code>
     * @return \Proto\TokenGetNftInfosResponse|null
     */
    public function getTokenGetNftInfos()
    {
        return $this->readOneof(156);
    }

    public function hasTokenGetNftInfos()
    {
        return $this->hasOneof(156);
    }

    /**
     **
     * A response for a query requesting detail for a subset of individual
     * non-fungible/unique tokens.<br/>
     * The requested tokens are selected by a list index, which is based
     * on the order in which the tokens were minted.
     *
     * Generated from protobuf field <code>.proto.TokenGetNftInfosResponse tokenGetNftInfos = 156;</code>
     * @param \Proto\TokenGetNftInfosResponse $var
     * @return $this
     */
    public function setTokenGetNftInfos($var)
    {
        GPBUtil::checkMessage($var, \Proto\TokenGetNftInfosResponse::class);
        $this->writeOneof(156, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting the time, in nanoseconds, spent
     * in direct processing for one or more recent transactions.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.NetworkGetExecutionTimeResponse networkGetExecutionTime = 157;</code>
     * @return \Proto\NetworkGetExecutionTimeResponse|null
     */
    public function getNetworkGetExecutionTime()
    {
        return $this->readOneof(157);
    }

    public function hasNetworkGetExecutionTime()
    {
        return $this->hasOneof(157);
    }

    /**
     **
     * A response for a query requesting the time, in nanoseconds, spent
     * in direct processing for one or more recent transactions.
     * <p>
     * > This query is no longer supported.
     *
     * Generated from protobuf field <code>.proto.NetworkGetExecutionTimeResponse networkGetExecutionTime = 157;</code>
     * @param \Proto\NetworkGetExecutionTimeResponse $var
     * @return $this
     */
    public function setNetworkGetExecutionTime($var)
    {
        GPBUtil::checkMessage($var, \Proto\NetworkGetExecutionTimeResponse::class);
        $this->writeOneof(157, $var);

        return $this;
    }

    /**
     **
     * A response for a query requesting detail information
     * about an account.
     * <p>
     * This query is a privileged query and "system" account authorization
     * is REQUIRED for this query.
     *
     * Generated from protobuf field <code>.proto.GetAccountDetailsResponse accountDetails = 158;</code>
     * @return \Proto\GetAccountDetailsResponse|null
     */
    public function getAccountDetails()
    {
        return $this->readOneof(158);
    }

    public function hasAccountDetails()
    {
        return $this->hasOneof(158);
    }

    /**
     **
     * A response for a query requesting detail information
     * about an account.
     * <p>
     * This query is a privileged query and "system" account authorization
     * is REQUIRED for this query.
     *
     * Generated from protobuf field <code>.proto.GetAccountDetailsResponse accountDetails = 158;</code>
     * @param \Proto\GetAccountDetailsResponse $var
     * @return $this
     */
    public function setAccountDetails($var)
    {
        GPBUtil::checkMessage($var, \Proto\GetAccountDetailsResponse::class);
        $this->writeOneof(158, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResponse()
    {
        return $this->whichOneof("response");
    }

}

