<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic_types.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * A software version according to "[semantic versioning](https://semver.org/)"
 * or "date versioning".
 * Hedera currently modifies the "typical" semantic versioning somewhat, the
 * `major` version is always `0`, and each release increments the `minor`
 * version. The `patch` and `pre` components are used in the typical manner.
 * The `build` component is not generally used.
 *
 * Generated from protobuf message <code>proto.SemanticVersion</code>
 */
class SemanticVersion extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * A major version.<br/>
     * Hedera does not increment this value and retains a `0` value to
     * indicate that API may change for any release.
     * <p>
     * This value SHALL increment for an incompatible API change.<br/>
     *
     * Generated from protobuf field <code>int32 major = 1;</code>
     */
    protected $major = 0;
    /**
     **
     * A minor version.<br/>
     * Hedera increments this value with each release.<br/>
     * There may be incompatible API changes in any Hedera Services release.
     * <p>
     * This value SHALL increment for backwards-compatible new
     * functionality.
     *
     * Generated from protobuf field <code>int32 minor = 2;</code>
     */
    protected $minor = 0;
    /**
     **
     * A patch version.
     * <p>
     * This value SHALL increment for backwards-compatible bug fixes.
     *
     * Generated from protobuf field <code>int32 patch = 3;</code>
     */
    protected $patch = 0;
    /**
     **
     * A pre-release version.
     * <p>
     * This MAY be denoted by appending a hyphen and a series of dot separated
     * identifiers per [Semver Specification](https://semver.org/#spec-item-9);
     * given a string `0.14.0-alpha.1+21AF26D3`, this field would contain
     * 'alpha.1'
     *
     * Generated from protobuf field <code>string pre = 4;</code>
     */
    protected $pre = '';
    /**
     **
     * A build version.
     * <p>
     * Build version MAY be denoted by appending a plus sign and a series of
     * dot separated identifiers immediately following the patch or pre-release
     * version per [Semver Specification](https://semver.org/#spec-item-10); so
     * given a string `0.14.0-alpha.1+21AF26D3`, this field
     * would contain '21AF26D3'
     *
     * Generated from protobuf field <code>string build = 5;</code>
     */
    protected $build = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $major
     *          *
     *           A major version.<br/>
     *           Hedera does not increment this value and retains a `0` value to
     *           indicate that API may change for any release.
     *           <p>
     *           This value SHALL increment for an incompatible API change.<br/>
     *     @type int $minor
     *          *
     *           A minor version.<br/>
     *           Hedera increments this value with each release.<br/>
     *           There may be incompatible API changes in any Hedera Services release.
     *           <p>
     *           This value SHALL increment for backwards-compatible new
     *           functionality.
     *     @type int $patch
     *          *
     *           A patch version.
     *           <p>
     *           This value SHALL increment for backwards-compatible bug fixes.
     *     @type string $pre
     *          *
     *           A pre-release version.
     *           <p>
     *           This MAY be denoted by appending a hyphen and a series of dot separated
     *           identifiers per [Semver Specification](https://semver.org/#spec-item-9);
     *           given a string `0.14.0-alpha.1+21AF26D3`, this field would contain
     *           'alpha.1'
     *     @type string $build
     *          *
     *           A build version.
     *           <p>
     *           Build version MAY be denoted by appending a plus sign and a series of
     *           dot separated identifiers immediately following the patch or pre-release
     *           version per [Semver Specification](https://semver.org/#spec-item-10); so
     *           given a string `0.14.0-alpha.1+21AF26D3`, this field
     *           would contain '21AF26D3'
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BasicTypes::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * A major version.<br/>
     * Hedera does not increment this value and retains a `0` value to
     * indicate that API may change for any release.
     * <p>
     * This value SHALL increment for an incompatible API change.<br/>
     *
     * Generated from protobuf field <code>int32 major = 1;</code>
     * @return int
     */
    public function getMajor()
    {
        return $this->major;
    }

    /**
     **
     * A major version.<br/>
     * Hedera does not increment this value and retains a `0` value to
     * indicate that API may change for any release.
     * <p>
     * This value SHALL increment for an incompatible API change.<br/>
     *
     * Generated from protobuf field <code>int32 major = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMajor($var)
    {
        GPBUtil::checkInt32($var);
        $this->major = $var;

        return $this;
    }

    /**
     **
     * A minor version.<br/>
     * Hedera increments this value with each release.<br/>
     * There may be incompatible API changes in any Hedera Services release.
     * <p>
     * This value SHALL increment for backwards-compatible new
     * functionality.
     *
     * Generated from protobuf field <code>int32 minor = 2;</code>
     * @return int
     */
    public function getMinor()
    {
        return $this->minor;
    }

    /**
     **
     * A minor version.<br/>
     * Hedera increments this value with each release.<br/>
     * There may be incompatible API changes in any Hedera Services release.
     * <p>
     * This value SHALL increment for backwards-compatible new
     * functionality.
     *
     * Generated from protobuf field <code>int32 minor = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMinor($var)
    {
        GPBUtil::checkInt32($var);
        $this->minor = $var;

        return $this;
    }

    /**
     **
     * A patch version.
     * <p>
     * This value SHALL increment for backwards-compatible bug fixes.
     *
     * Generated from protobuf field <code>int32 patch = 3;</code>
     * @return int
     */
    public function getPatch()
    {
        return $this->patch;
    }

    /**
     **
     * A patch version.
     * <p>
     * This value SHALL increment for backwards-compatible bug fixes.
     *
     * Generated from protobuf field <code>int32 patch = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPatch($var)
    {
        GPBUtil::checkInt32($var);
        $this->patch = $var;

        return $this;
    }

    /**
     **
     * A pre-release version.
     * <p>
     * This MAY be denoted by appending a hyphen and a series of dot separated
     * identifiers per [Semver Specification](https://semver.org/#spec-item-9);
     * given a string `0.14.0-alpha.1+21AF26D3`, this field would contain
     * 'alpha.1'
     *
     * Generated from protobuf field <code>string pre = 4;</code>
     * @return string
     */
    public function getPre()
    {
        return $this->pre;
    }

    /**
     **
     * A pre-release version.
     * <p>
     * This MAY be denoted by appending a hyphen and a series of dot separated
     * identifiers per [Semver Specification](https://semver.org/#spec-item-9);
     * given a string `0.14.0-alpha.1+21AF26D3`, this field would contain
     * 'alpha.1'
     *
     * Generated from protobuf field <code>string pre = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPre($var)
    {
        GPBUtil::checkString($var, True);
        $this->pre = $var;

        return $this;
    }

    /**
     **
     * A build version.
     * <p>
     * Build version MAY be denoted by appending a plus sign and a series of
     * dot separated identifiers immediately following the patch or pre-release
     * version per [Semver Specification](https://semver.org/#spec-item-10); so
     * given a string `0.14.0-alpha.1+21AF26D3`, this field
     * would contain '21AF26D3'
     *
     * Generated from protobuf field <code>string build = 5;</code>
     * @return string
     */
    public function getBuild()
    {
        return $this->build;
    }

    /**
     **
     * A build version.
     * <p>
     * Build version MAY be denoted by appending a plus sign and a series of
     * dot separated identifiers immediately following the patch or pre-release
     * version per [Semver Specification](https://semver.org/#spec-item-10); so
     * given a string `0.14.0-alpha.1+21AF26D3`, this field
     * would contain '21AF26D3'
     *
     * Generated from protobuf field <code>string build = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBuild($var)
    {
        GPBUtil::checkString($var, True);
        $this->build = $var;

        return $this;
    }

}

