<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic_types.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * This message is deprecated and MUST NOT be used to communicate with network
 * nodes. It is retained here only for historical reasons.
 * Client software MUST NOT include this message in any request. <br/>
 * Compliant nodes SHALL NOT accept any request containing this message.
 * Please use the `SignaturePair` and `SignatureMap` messages, in combination
 * with `ThresholdKey` keys, instead of this message.
 *
 * @deprecated
 * Generated from protobuf message <code>proto.ThresholdSignature</code>
 */
class ThresholdSignature extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * For an N-of-M threshold key, this is a list of M signatures, at least N
     * of which must be non-null.
     *
     * Generated from protobuf field <code>.proto.SignatureList sigs = 2;</code>
     */
    protected $sigs = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\SignatureList $sigs
     *          *
     *           For an N-of-M threshold key, this is a list of M signatures, at least N
     *           of which must be non-null.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BasicTypes::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * For an N-of-M threshold key, this is a list of M signatures, at least N
     * of which must be non-null.
     *
     * Generated from protobuf field <code>.proto.SignatureList sigs = 2;</code>
     * @return \Proto\SignatureList|null
     */
    public function getSigs()
    {
        return $this->sigs;
    }

    public function hasSigs()
    {
        return isset($this->sigs);
    }

    public function clearSigs()
    {
        unset($this->sigs);
    }

    /**
     **
     * For an N-of-M threshold key, this is a list of M signatures, at least N
     * of which must be non-null.
     *
     * Generated from protobuf field <code>.proto.SignatureList sigs = 2;</code>
     * @param \Proto\SignatureList $var
     * @return $this
     */
    public function setSigs($var)
    {
        GPBUtil::checkMessage($var, \Proto\SignatureList::class);
        $this->sigs = $var;

        return $this;
    }

}

