<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: throttle_definitions.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * A list of throttle buckets.<br/>
 * This list, simultaneously enforced, defines a complete throttling policy.
 *  1. When an operation appears in more than one throttling bucket,
 *     that operation SHALL be throttled unless all of the buckets where
 *     the operation appears have "capacity" available.
 *  1. An operation assigned to no buckets is SHALL be throttled in every
 *     instance.  The _effective_ throttle for this case is `0`.
 *
 * Generated from protobuf message <code>proto.ThrottleDefinitions</code>
 */
class ThrottleDefinitions extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * A list of throttle buckets.
     * <p>
     * This list MUST be set, and SHOULD NOT be empty.<br/>
     * An empty list SHALL have the effect of setting all operations to
     * a single group with throttle limit of `0` operations per second for the
     * entire network.
     *
     * Generated from protobuf field <code>repeated .proto.ThrottleBucket throttleBuckets = 1;</code>
     */
    private $throttleBuckets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\ThrottleBucket[] $throttleBuckets
     *          *
     *           A list of throttle buckets.
     *           <p>
     *           This list MUST be set, and SHOULD NOT be empty.<br/>
     *           An empty list SHALL have the effect of setting all operations to
     *           a single group with throttle limit of `0` operations per second for the
     *           entire network.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ThrottleDefinitions::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * A list of throttle buckets.
     * <p>
     * This list MUST be set, and SHOULD NOT be empty.<br/>
     * An empty list SHALL have the effect of setting all operations to
     * a single group with throttle limit of `0` operations per second for the
     * entire network.
     *
     * Generated from protobuf field <code>repeated .proto.ThrottleBucket throttleBuckets = 1;</code>
     * @return RepeatedField<\Proto\ThrottleBucket>
     */
    public function getThrottleBuckets()
    {
        return $this->throttleBuckets;
    }

    /**
     **
     * A list of throttle buckets.
     * <p>
     * This list MUST be set, and SHOULD NOT be empty.<br/>
     * An empty list SHALL have the effect of setting all operations to
     * a single group with throttle limit of `0` operations per second for the
     * entire network.
     *
     * Generated from protobuf field <code>repeated .proto.ThrottleBucket throttleBuckets = 1;</code>
     * @param \Proto\ThrottleBucket[] $var
     * @return $this
     */
    public function setThrottleBuckets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\ThrottleBucket::class);
        $this->throttleBuckets = $arr;

        return $this;
    }

}

