<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timestamp.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * An exact date and time.<br/>
 * This is the same data structure as the Google protobuf Timestamp.proto.
 * #### Additional Notes
 * Useful information is present in comments on the
 * [Google version](https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto).
 *
 * Generated from protobuf message <code>proto.Timestamp</code>
 */
class Timestamp extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * The number of complete seconds since the start of the epoch.
     * <p>
     * For this purpose, `epoch` SHALL be the UNIX epoch with 0
     * at `1970-01-01T00:00:00.000Z`.<br/>
     * This value MUST be greater than 0.<br/>
     * This value SHOULD be strictly greater than `946684800`.
     *
     * Generated from protobuf field <code>int64 seconds = 1;</code>
     */
    protected $seconds = 0;
    /**
     **
     * The number of nanoseconds after the start of the second referenced
     * in `seconds`.
     * <p>
     * This value MUST be greater than or equal to 0.<br/>
     * This value MUST be strictly less than 1,000,000,000.
     *
     * Generated from protobuf field <code>int32 nanos = 2;</code>
     */
    protected $nanos = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $seconds
     *          *
     *           The number of complete seconds since the start of the epoch.
     *           <p>
     *           For this purpose, `epoch` SHALL be the UNIX epoch with 0
     *           at `1970-01-01T00:00:00.000Z`.<br/>
     *           This value MUST be greater than 0.<br/>
     *           This value SHOULD be strictly greater than `946684800`.
     *     @type int $nanos
     *          *
     *           The number of nanoseconds after the start of the second referenced
     *           in `seconds`.
     *           <p>
     *           This value MUST be greater than or equal to 0.<br/>
     *           This value MUST be strictly less than 1,000,000,000.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Timestamp::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * The number of complete seconds since the start of the epoch.
     * <p>
     * For this purpose, `epoch` SHALL be the UNIX epoch with 0
     * at `1970-01-01T00:00:00.000Z`.<br/>
     * This value MUST be greater than 0.<br/>
     * This value SHOULD be strictly greater than `946684800`.
     *
     * Generated from protobuf field <code>int64 seconds = 1;</code>
     * @return int|string
     */
    public function getSeconds()
    {
        return $this->seconds;
    }

    /**
     **
     * The number of complete seconds since the start of the epoch.
     * <p>
     * For this purpose, `epoch` SHALL be the UNIX epoch with 0
     * at `1970-01-01T00:00:00.000Z`.<br/>
     * This value MUST be greater than 0.<br/>
     * This value SHOULD be strictly greater than `946684800`.
     *
     * Generated from protobuf field <code>int64 seconds = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeconds($var)
    {
        GPBUtil::checkInt64($var);
        $this->seconds = $var;

        return $this;
    }

    /**
     **
     * The number of nanoseconds after the start of the second referenced
     * in `seconds`.
     * <p>
     * This value MUST be greater than or equal to 0.<br/>
     * This value MUST be strictly less than 1,000,000,000.
     *
     * Generated from protobuf field <code>int32 nanos = 2;</code>
     * @return int
     */
    public function getNanos()
    {
        return $this->nanos;
    }

    /**
     **
     * The number of nanoseconds after the start of the second referenced
     * in `seconds`.
     * <p>
     * This value MUST be greater than or equal to 0.<br/>
     * This value MUST be strictly less than 1,000,000,000.
     *
     * Generated from protobuf field <code>int32 nanos = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNanos($var)
    {
        GPBUtil::checkInt32($var);
        $this->nanos = $var;

        return $this;
    }

}

