<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: token_get_account_nft_infos.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * Deleted and unsupported.
 *
 * Generated from protobuf message <code>proto.TokenGetAccountNftInfosResponse</code>
 */
class TokenGetAccountNftInfosResponse extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * The standard response information for queries.<br/>
     * This includes the values requested in the `QueryHeader`
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     **
     * List of NFTs associated to the account
     *
     * Generated from protobuf field <code>repeated .proto.TokenNftInfo nfts = 2;</code>
     */
    private $nfts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\ResponseHeader $header
     *          *
     *           The standard response information for queries.<br/>
     *           This includes the values requested in the `QueryHeader`
     *           (cost, state proof, both, or neither).
     *     @type \Proto\TokenNftInfo[] $nfts
     *          *
     *           List of NFTs associated to the account
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TokenGetAccountNftInfos::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * The standard response information for queries.<br/>
     * This includes the values requested in the `QueryHeader`
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.ResponseHeader header = 1;</code>
     * @return \Proto\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     **
     * The standard response information for queries.<br/>
     * This includes the values requested in the `QueryHeader`
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.ResponseHeader header = 1;</code>
     * @param \Proto\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Proto\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     **
     * List of NFTs associated to the account
     *
     * Generated from protobuf field <code>repeated .proto.TokenNftInfo nfts = 2;</code>
     * @return RepeatedField<\Proto\TokenNftInfo>
     */
    public function getNfts()
    {
        return $this->nfts;
    }

    /**
     **
     * List of NFTs associated to the account
     *
     * Generated from protobuf field <code>repeated .proto.TokenNftInfo nfts = 2;</code>
     * @param \Proto\TokenNftInfo[] $var
     * @return $this
     */
    public function setNfts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\TokenNftInfo::class);
        $this->nfts = $arr;

        return $this;
    }

}

