<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: token_get_account_nft_infos.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * Deleted and unsupported.
 * This query is not implemented and any query of this type submitted
 * SHALL return a `NOT_SUPPORTED` response code.
 *
 * Generated from protobuf message <code>proto.TokenGetAccountNftInfosQuery</code>
 */
class TokenGetAccountNftInfosQuery extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * Standard information sent with every query operation.<br/>
     * This includes the signed payment and what kind of response is requested
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.QueryHeader header = 1;</code>
     */
    protected $header = null;
    /**
     **
     * The Account for which information is requested
     *
     * Generated from protobuf field <code>.proto.AccountID accountID = 2;</code>
     */
    protected $accountID = null;
    /**
     **
     * Specifies the start index (inclusive) of the range of NFTs to query for.
     * Value must be in the range [0; ownedNFTs-1]
     *
     * Generated from protobuf field <code>int64 start = 3;</code>
     */
    protected $start = 0;
    /**
     **
     * Specifies the end index (exclusive) of the range of NFTs to query for.
     * Value must be in the range (start; ownedNFTs]
     *
     * Generated from protobuf field <code>int64 end = 4;</code>
     */
    protected $end = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\QueryHeader $header
     *          *
     *           Standard information sent with every query operation.<br/>
     *           This includes the signed payment and what kind of response is requested
     *           (cost, state proof, both, or neither).
     *     @type \Proto\AccountID $accountID
     *          *
     *           The Account for which information is requested
     *     @type int|string $start
     *          *
     *           Specifies the start index (inclusive) of the range of NFTs to query for.
     *           Value must be in the range [0; ownedNFTs-1]
     *     @type int|string $end
     *          *
     *           Specifies the end index (exclusive) of the range of NFTs to query for.
     *           Value must be in the range (start; ownedNFTs]
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TokenGetAccountNftInfos::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * Standard information sent with every query operation.<br/>
     * This includes the signed payment and what kind of response is requested
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.QueryHeader header = 1;</code>
     * @return \Proto\QueryHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     **
     * Standard information sent with every query operation.<br/>
     * This includes the signed payment and what kind of response is requested
     * (cost, state proof, both, or neither).
     *
     * Generated from protobuf field <code>.proto.QueryHeader header = 1;</code>
     * @param \Proto\QueryHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Proto\QueryHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     **
     * The Account for which information is requested
     *
     * Generated from protobuf field <code>.proto.AccountID accountID = 2;</code>
     * @return \Proto\AccountID|null
     */
    public function getAccountID()
    {
        return $this->accountID;
    }

    public function hasAccountID()
    {
        return isset($this->accountID);
    }

    public function clearAccountID()
    {
        unset($this->accountID);
    }

    /**
     **
     * The Account for which information is requested
     *
     * Generated from protobuf field <code>.proto.AccountID accountID = 2;</code>
     * @param \Proto\AccountID $var
     * @return $this
     */
    public function setAccountID($var)
    {
        GPBUtil::checkMessage($var, \Proto\AccountID::class);
        $this->accountID = $var;

        return $this;
    }

    /**
     **
     * Specifies the start index (inclusive) of the range of NFTs to query for.
     * Value must be in the range [0; ownedNFTs-1]
     *
     * Generated from protobuf field <code>int64 start = 3;</code>
     * @return int|string
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     **
     * Specifies the start index (inclusive) of the range of NFTs to query for.
     * Value must be in the range [0; ownedNFTs-1]
     *
     * Generated from protobuf field <code>int64 start = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkInt64($var);
        $this->start = $var;

        return $this;
    }

    /**
     **
     * Specifies the end index (exclusive) of the range of NFTs to query for.
     * Value must be in the range (start; ownedNFTs]
     *
     * Generated from protobuf field <code>int64 end = 4;</code>
     * @return int|string
     */
    public function getEnd()
    {
        return $this->end;
    }

    /**
     **
     * Specifies the end index (exclusive) of the range of NFTs to query for.
     * Value must be in the range (start; ownedNFTs]
     *
     * Generated from protobuf field <code>int64 end = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEnd($var)
    {
        GPBUtil::checkInt64($var);
        $this->end = $var;

        return $this;
    }

}

