<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_response.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * A message sent by a node in response to a transaction submission.<br/>
 * This message only acknowledges that the individual node has checked
 * the transaction, completed pre-check, and checked the fee offered.
 * If the transaction fee is not sufficient, the `nodeTransactionPrecheckCode`
 * value SHALL be `INSUFFICIENT_TX_FEE` and the `cost` field SHALL be the
 * actual transaction fee, in tinybar, required.<br/>
 * If the client requires acknowledgement of the network consensus result
 * for a transaction, the client SHOULD request a transaction receipt or
 * detailed transaction record. A client MAY also obtain network consensus
 * results from a mirror node.
 *
 * Generated from protobuf message <code>proto.TransactionResponse</code>
 */
class TransactionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * A pre-consensus response code.
     * <p>
     * This response SHALL represent the response of the individual node, and
     * SHALL NOT represent the consensus of the network.
     *
     * Generated from protobuf field <code>.proto.ResponseCodeEnum nodeTransactionPrecheckCode = 1;</code>
     */
    protected $nodeTransactionPrecheckCode = 0;
    /**
     **
     * An approximate transaction fee.
     * <p>
     * This value SHALL be `0` unless the `nodeTransactionPrecheckCode` is
     * `INSUFFICIENT_TX_FEE`.<br/>
     * This value SHOULD be an amount, in tinybar, that _would have_ succeeded
     * at the time the transaction was submitted.<br/>
     * Note that this amount is not guaranteed to succeed in a future
     * transaction due to uncontrolled variables, such as network congestion,
     * but should be considered a close approximation.
     *
     * Generated from protobuf field <code>uint64 cost = 2;</code>
     */
    protected $cost = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $nodeTransactionPrecheckCode
     *          *
     *           A pre-consensus response code.
     *           <p>
     *           This response SHALL represent the response of the individual node, and
     *           SHALL NOT represent the consensus of the network.
     *     @type int|string $cost
     *          *
     *           An approximate transaction fee.
     *           <p>
     *           This value SHALL be `0` unless the `nodeTransactionPrecheckCode` is
     *           `INSUFFICIENT_TX_FEE`.<br/>
     *           This value SHOULD be an amount, in tinybar, that _would have_ succeeded
     *           at the time the transaction was submitted.<br/>
     *           Note that this amount is not guaranteed to succeed in a future
     *           transaction due to uncontrolled variables, such as network congestion,
     *           but should be considered a close approximation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TransactionResponse::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * A pre-consensus response code.
     * <p>
     * This response SHALL represent the response of the individual node, and
     * SHALL NOT represent the consensus of the network.
     *
     * Generated from protobuf field <code>.proto.ResponseCodeEnum nodeTransactionPrecheckCode = 1;</code>
     * @return int
     */
    public function getNodeTransactionPrecheckCode()
    {
        return $this->nodeTransactionPrecheckCode;
    }

    /**
     **
     * A pre-consensus response code.
     * <p>
     * This response SHALL represent the response of the individual node, and
     * SHALL NOT represent the consensus of the network.
     *
     * Generated from protobuf field <code>.proto.ResponseCodeEnum nodeTransactionPrecheckCode = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNodeTransactionPrecheckCode($var)
    {
        GPBUtil::checkEnum($var, \Proto\ResponseCodeEnum::class);
        $this->nodeTransactionPrecheckCode = $var;

        return $this;
    }

    /**
     **
     * An approximate transaction fee.
     * <p>
     * This value SHALL be `0` unless the `nodeTransactionPrecheckCode` is
     * `INSUFFICIENT_TX_FEE`.<br/>
     * This value SHOULD be an amount, in tinybar, that _would have_ succeeded
     * at the time the transaction was submitted.<br/>
     * Note that this amount is not guaranteed to succeed in a future
     * transaction due to uncontrolled variables, such as network congestion,
     * but should be considered a close approximation.
     *
     * Generated from protobuf field <code>uint64 cost = 2;</code>
     * @return int|string
     */
    public function getCost()
    {
        return $this->cost;
    }

    /**
     **
     * An approximate transaction fee.
     * <p>
     * This value SHALL be `0` unless the `nodeTransactionPrecheckCode` is
     * `INSUFFICIENT_TX_FEE`.<br/>
     * This value SHOULD be an amount, in tinybar, that _would have_ succeeded
     * at the time the transaction was submitted.<br/>
     * Note that this amount is not guaranteed to succeed in a future
     * transaction due to uncontrolled variables, such as network congestion,
     * but should be considered a close approximation.
     *
     * Generated from protobuf field <code>uint64 cost = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCost($var)
    {
        GPBUtil::checkUint64($var);
        $this->cost = $var;

        return $this;
    }

}

