<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auxiliary/hints/crs_publication.proto

namespace Com\Hedera\Hapi\Services\Auxiliary\Hints;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * A transaction body to publish a node's Common Reference String (CRS) to the network. This is used
 * when node wants to update to reach the final CRS for network to use the hinTS protocol
 *
 * Generated from protobuf message <code>com.hedera.hapi.services.auxiliary.hints.CrsPublicationTransactionBody</code>
 */
class CrsPublicationTransactionBody extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * The party's generated random CRS.
     *
     * Generated from protobuf field <code>bytes new_crs = 1;</code>
     */
    protected $new_crs = '';
    /**
     **
     * The party's proof of the CRS update.
     *
     * Generated from protobuf field <code>bytes proof = 2;</code>
     */
    protected $proof = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $new_crs
     *          *
     *           The party's generated random CRS.
     *     @type string $proof
     *          *
     *           The party's proof of the CRS update.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auxiliary\Hints\CrsPublication::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * The party's generated random CRS.
     *
     * Generated from protobuf field <code>bytes new_crs = 1;</code>
     * @return string
     */
    public function getNewCrs()
    {
        return $this->new_crs;
    }

    /**
     **
     * The party's generated random CRS.
     *
     * Generated from protobuf field <code>bytes new_crs = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNewCrs($var)
    {
        GPBUtil::checkString($var, False);
        $this->new_crs = $var;

        return $this;
    }

    /**
     **
     * The party's proof of the CRS update.
     *
     * Generated from protobuf field <code>bytes proof = 2;</code>
     * @return string
     */
    public function getProof()
    {
        return $this->proof;
    }

    /**
     **
     * The party's proof of the CRS update.
     *
     * Generated from protobuf field <code>bytes proof = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setProof($var)
    {
        GPBUtil::checkString($var, False);
        $this->proof = $var;

        return $this;
    }

}

