<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mirror_network_service.proto

namespace GPBMetadata;

class MirrorNetworkService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x9B\x02\x0A\x1Cmirror_network_service.proto\x12\x1Bcom.hedera.mirror.api.proto\x1A\x0Ftimestamp.proto\"A\x0A\x10AddressBookQuery\x12\x1E\x0A\x07file_id\x18\x01 \x01(\x0B2\x0D.proto.FileID\x12\x0D\x0A\x05limit\x18\x02 \x01(\x052a\x0A\x0ENetworkService\x12O\x0A\x08getNodes\x12-.com.hedera.mirror.api.proto.AddressBookQuery\x1A\x12.proto.NodeAddress0\x01B\x1F\x0A\x1Bcom.hedera.mirror.api.protoP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

