<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auxiliary/history/history_proof_key_publication.proto

namespace GPBMetadata\Auxiliary\History;

class HistoryProofKeyPublication
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE2\x01\x0A5auxiliary/history/history_proof_key_publication.proto\x12*com.hedera.hapi.services.auxiliary.history\">\x0A)HistoryProofKeyPublicationTransactionBody\x12\x11\x0A\x09proof_key\x18\x01 \x01(\x0CB5\x0A1com.hedera.hapi.services.auxiliary.history.legacyP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

