<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event/event_core.proto

namespace Com\Hedera\Hapi\Platform\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * Contains information about an event and its parents.
 *
 * Generated from protobuf message <code>com.hedera.hapi.platform.event.EventCore</code>
 */
class EventCore extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * The creator node identifier.<br/>
     * This SHALL be the unique identifier for the node that created the event.<br/>
     * This SHALL match the ID of the node as it appears in the address book.
     *
     * Generated from protobuf field <code>int64 creator_node_id = 1;</code>
     */
    protected $creator_node_id = 0;
    /**
     **
     * The birth round of the event.<br/>
     * The birth round SHALL be the pending consensus round at the time the event is created.<br/>
     * The pending consensus round SHALL be **one greater** than the latest round to reach consensus.
     *
     * Generated from protobuf field <code>int64 birth_round = 2;</code>
     */
    protected $birth_round = 0;
    /**
     **
     * The wall clock time at which the event was created, according to the node creating the event.<br/>
     * If the event has a self parent, this timestamp MUST be strictly greater than the `time_created` of the self parent.
     *
     * Generated from protobuf field <code>.proto.Timestamp time_created = 3;</code>
     */
    protected $time_created = null;
    /**
     **
     * A list of EventDescriptors representing the parents of this event.<br/>
     * The list of parents SHALL include zero or one self parents, and zero or more other parents.<br/>
     * The first element of the list SHALL be the self parent, if one exists.<br/>
     * The list of parents SHALL NOT include more than one parent from the same creator.
     * <p>
     * This field is deprecated and can be removed in release 0.62
     *
     * Generated from protobuf field <code>repeated .com.hedera.hapi.platform.event.EventDescriptor parents = 4 [deprecated = true];</code>
     * @deprecated
     */
    private $parents;
    /**
     **
     * The event specification version.<br/>
     * The specification described by this version SHALL encompass the format of the `GossipEvent` message, and also the
     * format of all contained messages.<br/>
     * This SHALL exactly match the specification version passed into the platform at construction.
     *
     * Generated from protobuf field <code>.proto.SemanticVersion version = 17;</code>
     */
    protected $version = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $creator_node_id
     *          *
     *           The creator node identifier.<br/>
     *           This SHALL be the unique identifier for the node that created the event.<br/>
     *           This SHALL match the ID of the node as it appears in the address book.
     *     @type int|string $birth_round
     *          *
     *           The birth round of the event.<br/>
     *           The birth round SHALL be the pending consensus round at the time the event is created.<br/>
     *           The pending consensus round SHALL be **one greater** than the latest round to reach consensus.
     *     @type \Proto\Timestamp $time_created
     *          *
     *           The wall clock time at which the event was created, according to the node creating the event.<br/>
     *           If the event has a self parent, this timestamp MUST be strictly greater than the `time_created` of the self parent.
     *     @type \Com\Hedera\Hapi\Platform\Event\EventDescriptor[] $parents
     *          *
     *           A list of EventDescriptors representing the parents of this event.<br/>
     *           The list of parents SHALL include zero or one self parents, and zero or more other parents.<br/>
     *           The first element of the list SHALL be the self parent, if one exists.<br/>
     *           The list of parents SHALL NOT include more than one parent from the same creator.
     *           <p>
     *           This field is deprecated and can be removed in release 0.62
     *     @type \Proto\SemanticVersion $version
     *          *
     *           The event specification version.<br/>
     *           The specification described by this version SHALL encompass the format of the `GossipEvent` message, and also the
     *           format of all contained messages.<br/>
     *           This SHALL exactly match the specification version passed into the platform at construction.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event\EventCore::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * The creator node identifier.<br/>
     * This SHALL be the unique identifier for the node that created the event.<br/>
     * This SHALL match the ID of the node as it appears in the address book.
     *
     * Generated from protobuf field <code>int64 creator_node_id = 1;</code>
     * @return int|string
     */
    public function getCreatorNodeId()
    {
        return $this->creator_node_id;
    }

    /**
     **
     * The creator node identifier.<br/>
     * This SHALL be the unique identifier for the node that created the event.<br/>
     * This SHALL match the ID of the node as it appears in the address book.
     *
     * Generated from protobuf field <code>int64 creator_node_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatorNodeId($var)
    {
        GPBUtil::checkInt64($var);
        $this->creator_node_id = $var;

        return $this;
    }

    /**
     **
     * The birth round of the event.<br/>
     * The birth round SHALL be the pending consensus round at the time the event is created.<br/>
     * The pending consensus round SHALL be **one greater** than the latest round to reach consensus.
     *
     * Generated from protobuf field <code>int64 birth_round = 2;</code>
     * @return int|string
     */
    public function getBirthRound()
    {
        return $this->birth_round;
    }

    /**
     **
     * The birth round of the event.<br/>
     * The birth round SHALL be the pending consensus round at the time the event is created.<br/>
     * The pending consensus round SHALL be **one greater** than the latest round to reach consensus.
     *
     * Generated from protobuf field <code>int64 birth_round = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBirthRound($var)
    {
        GPBUtil::checkInt64($var);
        $this->birth_round = $var;

        return $this;
    }

    /**
     **
     * The wall clock time at which the event was created, according to the node creating the event.<br/>
     * If the event has a self parent, this timestamp MUST be strictly greater than the `time_created` of the self parent.
     *
     * Generated from protobuf field <code>.proto.Timestamp time_created = 3;</code>
     * @return \Proto\Timestamp|null
     */
    public function getTimeCreated()
    {
        return $this->time_created;
    }

    public function hasTimeCreated()
    {
        return isset($this->time_created);
    }

    public function clearTimeCreated()
    {
        unset($this->time_created);
    }

    /**
     **
     * The wall clock time at which the event was created, according to the node creating the event.<br/>
     * If the event has a self parent, this timestamp MUST be strictly greater than the `time_created` of the self parent.
     *
     * Generated from protobuf field <code>.proto.Timestamp time_created = 3;</code>
     * @param \Proto\Timestamp $var
     * @return $this
     */
    public function setTimeCreated($var)
    {
        GPBUtil::checkMessage($var, \Proto\Timestamp::class);
        $this->time_created = $var;

        return $this;
    }

    /**
     **
     * A list of EventDescriptors representing the parents of this event.<br/>
     * The list of parents SHALL include zero or one self parents, and zero or more other parents.<br/>
     * The first element of the list SHALL be the self parent, if one exists.<br/>
     * The list of parents SHALL NOT include more than one parent from the same creator.
     * <p>
     * This field is deprecated and can be removed in release 0.62
     *
     * Generated from protobuf field <code>repeated .com.hedera.hapi.platform.event.EventDescriptor parents = 4 [deprecated = true];</code>
     * @return RepeatedField<\Com\Hedera\Hapi\Platform\Event\EventDescriptor>
     * @deprecated
     */
    public function getParents()
    {
        if ($this->parents->count() !== 0) {
            @trigger_error('parents is deprecated.', E_USER_DEPRECATED);
        }
        return $this->parents;
    }

    /**
     **
     * A list of EventDescriptors representing the parents of this event.<br/>
     * The list of parents SHALL include zero or one self parents, and zero or more other parents.<br/>
     * The first element of the list SHALL be the self parent, if one exists.<br/>
     * The list of parents SHALL NOT include more than one parent from the same creator.
     * <p>
     * This field is deprecated and can be removed in release 0.62
     *
     * Generated from protobuf field <code>repeated .com.hedera.hapi.platform.event.EventDescriptor parents = 4 [deprecated = true];</code>
     * @param \Com\Hedera\Hapi\Platform\Event\EventDescriptor[] $var
     * @return $this
     * @deprecated
     */
    public function setParents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Com\Hedera\Hapi\Platform\Event\EventDescriptor::class);
        if ($arr->count() !== 0) {
            @trigger_error('parents is deprecated.', E_USER_DEPRECATED);
        }
        $this->parents = $arr;

        return $this;
    }

    /**
     **
     * The event specification version.<br/>
     * The specification described by this version SHALL encompass the format of the `GossipEvent` message, and also the
     * format of all contained messages.<br/>
     * This SHALL exactly match the specification version passed into the platform at construction.
     *
     * Generated from protobuf field <code>.proto.SemanticVersion version = 17;</code>
     * @return \Proto\SemanticVersion|null
     */
    public function getVersion()
    {
        return $this->version;
    }

    public function hasVersion()
    {
        return isset($this->version);
    }

    public function clearVersion()
    {
        unset($this->version);
    }

    /**
     **
     * The event specification version.<br/>
     * The specification described by this version SHALL encompass the format of the `GossipEvent` message, and also the
     * format of all contained messages.<br/>
     * This SHALL exactly match the specification version passed into the platform at construction.
     *
     * Generated from protobuf field <code>.proto.SemanticVersion version = 17;</code>
     * @param \Proto\SemanticVersion $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkMessage($var, \Proto\SemanticVersion::class);
        $this->version = $var;

        return $this;
    }

}

