<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event/gossip_event.proto

namespace Com\Hedera\Hapi\Platform\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * An event that is sent and received via gossip
 *
 * Generated from protobuf message <code>com.hedera.hapi.platform.event.GossipEvent</code>
 */
class GossipEvent extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * The core event data
     *
     * Generated from protobuf field <code>.com.hedera.hapi.platform.event.EventCore event_core = 1;</code>
     */
    protected $event_core = null;
    /**
     **
     * A node signature on the event hash.<br/>
     * The signature SHALL be created with the SHA384withRSA algorithm.<br/>
     * The signature MUST verify using the public key belonging to the `event_creator`.<br/>
     * The `event_creator` public key SHALL be read from the address book that corresponds to the event's birth round.<br/>
     * The signed event hash SHALL be a SHA-384 hash.<br/>
     * The signed event hash SHALL have the following inputs, in the specified order:<br/>
     * 1. The bytes of the `event_core` field<br/>
     * 2. The SHA-384 hash of each individual `EventTransaction`, in the order the transaction appear in the `event_transaction` field
     *
     * Generated from protobuf field <code>bytes signature = 2;</code>
     */
    protected $signature = '';
    /**
     **
     * A list of serialized transactions.
     * <p>
     * This field MAY contain zero transactions.<br/>
     * Each transaction in this list SHALL be presented exactly as
     * it was supplied to the consensus algorithm.<br/>
     * This field MUST contain one entry for each transaction
     * included in this gossip event.
     *
     * Generated from protobuf field <code>repeated bytes transactions = 4;</code>
     */
    private $transactions;
    /**
     **
     * A list of EventDescriptors representing the parents of this event.<br/>
     * The list of parents SHALL include zero or one self parents, and zero or more other parents.<br/>
     * The first element of the list SHALL be the self parent, if one exists.<br/>
     * The list of parents SHALL NOT include more than one parent from the same creator.
     * <p>
     * NOTE: This field is currently being migrated from EventCore to GossipEvent.
     * Once the migration is complete, this field will be removed from EventCore.
     * While migration is ongoing, the expectation is that only one of the two
     * fields will be set, but not both.
     *
     * Generated from protobuf field <code>repeated .com.hedera.hapi.platform.event.EventDescriptor parents = 5;</code>
     */
    private $parents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Com\Hedera\Hapi\Platform\Event\EventCore $event_core
     *          *
     *           The core event data
     *     @type string $signature
     *          *
     *           A node signature on the event hash.<br/>
     *           The signature SHALL be created with the SHA384withRSA algorithm.<br/>
     *           The signature MUST verify using the public key belonging to the `event_creator`.<br/>
     *           The `event_creator` public key SHALL be read from the address book that corresponds to the event's birth round.<br/>
     *           The signed event hash SHALL be a SHA-384 hash.<br/>
     *           The signed event hash SHALL have the following inputs, in the specified order:<br/>
     *           1. The bytes of the `event_core` field<br/>
     *           2. The SHA-384 hash of each individual `EventTransaction`, in the order the transaction appear in the `event_transaction` field
     *     @type string[] $transactions
     *          *
     *           A list of serialized transactions.
     *           <p>
     *           This field MAY contain zero transactions.<br/>
     *           Each transaction in this list SHALL be presented exactly as
     *           it was supplied to the consensus algorithm.<br/>
     *           This field MUST contain one entry for each transaction
     *           included in this gossip event.
     *     @type \Com\Hedera\Hapi\Platform\Event\EventDescriptor[] $parents
     *          *
     *           A list of EventDescriptors representing the parents of this event.<br/>
     *           The list of parents SHALL include zero or one self parents, and zero or more other parents.<br/>
     *           The first element of the list SHALL be the self parent, if one exists.<br/>
     *           The list of parents SHALL NOT include more than one parent from the same creator.
     *           <p>
     *           NOTE: This field is currently being migrated from EventCore to GossipEvent.
     *           Once the migration is complete, this field will be removed from EventCore.
     *           While migration is ongoing, the expectation is that only one of the two
     *           fields will be set, but not both.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event\GossipEvent::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * The core event data
     *
     * Generated from protobuf field <code>.com.hedera.hapi.platform.event.EventCore event_core = 1;</code>
     * @return \Com\Hedera\Hapi\Platform\Event\EventCore|null
     */
    public function getEventCore()
    {
        return $this->event_core;
    }

    public function hasEventCore()
    {
        return isset($this->event_core);
    }

    public function clearEventCore()
    {
        unset($this->event_core);
    }

    /**
     **
     * The core event data
     *
     * Generated from protobuf field <code>.com.hedera.hapi.platform.event.EventCore event_core = 1;</code>
     * @param \Com\Hedera\Hapi\Platform\Event\EventCore $var
     * @return $this
     */
    public function setEventCore($var)
    {
        GPBUtil::checkMessage($var, \Com\Hedera\Hapi\Platform\Event\EventCore::class);
        $this->event_core = $var;

        return $this;
    }

    /**
     **
     * A node signature on the event hash.<br/>
     * The signature SHALL be created with the SHA384withRSA algorithm.<br/>
     * The signature MUST verify using the public key belonging to the `event_creator`.<br/>
     * The `event_creator` public key SHALL be read from the address book that corresponds to the event's birth round.<br/>
     * The signed event hash SHALL be a SHA-384 hash.<br/>
     * The signed event hash SHALL have the following inputs, in the specified order:<br/>
     * 1. The bytes of the `event_core` field<br/>
     * 2. The SHA-384 hash of each individual `EventTransaction`, in the order the transaction appear in the `event_transaction` field
     *
     * Generated from protobuf field <code>bytes signature = 2;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     **
     * A node signature on the event hash.<br/>
     * The signature SHALL be created with the SHA384withRSA algorithm.<br/>
     * The signature MUST verify using the public key belonging to the `event_creator`.<br/>
     * The `event_creator` public key SHALL be read from the address book that corresponds to the event's birth round.<br/>
     * The signed event hash SHALL be a SHA-384 hash.<br/>
     * The signed event hash SHALL have the following inputs, in the specified order:<br/>
     * 1. The bytes of the `event_core` field<br/>
     * 2. The SHA-384 hash of each individual `EventTransaction`, in the order the transaction appear in the `event_transaction` field
     *
     * Generated from protobuf field <code>bytes signature = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

    /**
     **
     * A list of serialized transactions.
     * <p>
     * This field MAY contain zero transactions.<br/>
     * Each transaction in this list SHALL be presented exactly as
     * it was supplied to the consensus algorithm.<br/>
     * This field MUST contain one entry for each transaction
     * included in this gossip event.
     *
     * Generated from protobuf field <code>repeated bytes transactions = 4;</code>
     * @return RepeatedField<string>
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     **
     * A list of serialized transactions.
     * <p>
     * This field MAY contain zero transactions.<br/>
     * Each transaction in this list SHALL be presented exactly as
     * it was supplied to the consensus algorithm.<br/>
     * This field MUST contain one entry for each transaction
     * included in this gossip event.
     *
     * Generated from protobuf field <code>repeated bytes transactions = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->transactions = $arr;

        return $this;
    }

    /**
     **
     * A list of EventDescriptors representing the parents of this event.<br/>
     * The list of parents SHALL include zero or one self parents, and zero or more other parents.<br/>
     * The first element of the list SHALL be the self parent, if one exists.<br/>
     * The list of parents SHALL NOT include more than one parent from the same creator.
     * <p>
     * NOTE: This field is currently being migrated from EventCore to GossipEvent.
     * Once the migration is complete, this field will be removed from EventCore.
     * While migration is ongoing, the expectation is that only one of the two
     * fields will be set, but not both.
     *
     * Generated from protobuf field <code>repeated .com.hedera.hapi.platform.event.EventDescriptor parents = 5;</code>
     * @return RepeatedField<\Com\Hedera\Hapi\Platform\Event\EventDescriptor>
     */
    public function getParents()
    {
        return $this->parents;
    }

    /**
     **
     * A list of EventDescriptors representing the parents of this event.<br/>
     * The list of parents SHALL include zero or one self parents, and zero or more other parents.<br/>
     * The first element of the list SHALL be the self parent, if one exists.<br/>
     * The list of parents SHALL NOT include more than one parent from the same creator.
     * <p>
     * NOTE: This field is currently being migrated from EventCore to GossipEvent.
     * Once the migration is complete, this field will be removed from EventCore.
     * While migration is ongoing, the expectation is that only one of the two
     * fields will be set, but not both.
     *
     * Generated from protobuf field <code>repeated .com.hedera.hapi.platform.event.EventDescriptor parents = 5;</code>
     * @param \Com\Hedera\Hapi\Platform\Event\EventDescriptor[] $var
     * @return $this
     */
    public function setParents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Com\Hedera\Hapi\Platform\Event\EventDescriptor::class);
        $this->parents = $arr;

        return $this;
    }

}

