<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event/event_core.proto

namespace GPBMetadata\Event;

class EventCore
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        \GPBMetadata\Event\EventDescriptor::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xED\x02\x0A\x16event/event_core.proto\x12\x1Ecom.hedera.hapi.platform.event\x1A\x1Cevent/event_descriptor.proto\x1A\x0Ftimestamp.proto\"\xD0\x01\x0A\x09EventCore\x12\x17\x0A\x0Fcreator_node_id\x18\x01 \x01(\x03\x12\x13\x0A\x0Bbirth_round\x18\x02 \x01(\x03\x12&\x0A\x0Ctime_created\x18\x03 \x01(\x0B2\x10.proto.Timestamp\x12D\x0A\x07parents\x18\x04 \x03(\x0B2/.com.hedera.hapi.platform.event.EventDescriptorB\x02\x18\x01\x12'\x0A\x07version\x18\x11 \x01(\x0B2\x16.proto.SemanticVersionB)\x0A%com.hedera.hapi.platform.event.legacyP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

