<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: consensus_service.proto

namespace GPBMetadata;

class ConsensusService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Query::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\TransactionResponse::initOnce();
        \GPBMetadata\Transaction::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD3\x03\x0A\x17consensus_service.proto\x12\x05proto\x1A\x0Eresponse.proto\x1A\x1Atransaction_response.proto\x1A\x11transaction.proto2\xBF\x02\x0A\x10ConsensusService\x12=\x0A\x0BcreateTopic\x12\x12.proto.Transaction\x1A\x1A.proto.TransactionResponse\x12=\x0A\x0BupdateTopic\x12\x12.proto.Transaction\x1A\x1A.proto.TransactionResponse\x12=\x0A\x0BdeleteTopic\x12\x12.proto.Transaction\x1A\x1A.proto.TransactionResponse\x12?\x0A\x0DsubmitMessage\x12\x12.proto.Transaction\x1A\x1A.proto.TransactionResponse\x12-\x0A\x0CgetTopicInfo\x12\x0C.proto.Query\x1A\x0F.proto.ResponseB(\x0A&com.hederahashgraph.service.proto.javab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

