<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contract_update.proto

namespace GPBMetadata;

class ContractUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        \GPBMetadata\Duration::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF3\x05\x0A\x15contract_update.proto\x12\x05proto\x1A\x0Eduration.proto\x1A\x0Ftimestamp.proto\x1A\x1Egoogle/protobuf/wrappers.proto\"\xE1\x04\x0A\x1DContractUpdateTransactionBody\x12%\x0A\x0AcontractID\x18\x01 \x01(\x0B2\x11.proto.ContractID\x12(\x0A\x0EexpirationTime\x18\x02 \x01(\x0B2\x10.proto.Timestamp\x12\x1C\x0A\x08adminKey\x18\x03 \x01(\x0B2\x0A.proto.Key\x12,\x0A\x0EproxyAccountID\x18\x06 \x01(\x0B2\x10.proto.AccountIDB\x02\x18\x01\x12(\x0A\x0FautoRenewPeriod\x18\x07 \x01(\x0B2\x0F.proto.Duration\x12!\x0A\x06fileID\x18\x08 \x01(\x0B2\x0D.proto.FileIDB\x02\x18\x01\x12\x12\x0A\x04memo\x18\x09 \x01(\x09B\x02\x18\x01H\x00\x123\x0A\x0BmemoWrapper\x18\x0A \x01(\x0B2\x1C.google.protobuf.StringValueH\x00\x12E\x0A max_automatic_token_associations\x18\x0B \x01(\x0B2\x1B.google.protobuf.Int32Value\x12/\x0A\x15auto_renew_account_id\x18\x0C \x01(\x0B2\x10.proto.AccountID\x12-\x0A\x11staked_account_id\x18\x0D \x01(\x0B2\x10.proto.AccountIDH\x01\x12\x18\x0A\x0Estaked_node_id\x18\x0E \x01(\x03H\x01\x122\x0A\x0Edecline_reward\x18\x0F \x01(\x0B2\x1A.google.protobuf.BoolValueB\x0B\x0A\x09memoFieldB\x0B\x0A\x09staked_idB&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

