<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contract_call_local.proto

namespace GPBMetadata;

class ContractCallLocal
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        \GPBMetadata\ContractTypes::initOnce();
        \GPBMetadata\QueryHeader::initOnce();
        \GPBMetadata\ResponseHeader::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDD\x03\x0A\x19contract_call_local.proto\x12\x05proto\x1A\x14contract_types.proto\x1A\x12query_header.proto\x1A\x15response_header.proto\"\xCC\x01\x0A\x16ContractCallLocalQuery\x12\"\x0A\x06header\x18\x01 \x01(\x0B2\x12.proto.QueryHeader\x12%\x0A\x0AcontractID\x18\x02 \x01(\x0B2\x11.proto.ContractID\x12\x0B\x0A\x03gas\x18\x03 \x01(\x03\x12\x1A\x0A\x12functionParameters\x18\x04 \x01(\x0C\x12\x19\x0A\x0DmaxResultSize\x18\x05 \x01(\x03B\x02\x18\x01\x12#\x0A\x09sender_id\x18\x06 \x01(\x0B2\x10.proto.AccountID\"y\x0A\x19ContractCallLocalResponse\x12%\x0A\x06header\x18\x01 \x01(\x0B2\x15.proto.ResponseHeader\x125\x0A\x0EfunctionResult\x18\x02 \x01(\x0B2\x1D.proto.ContractFunctionResultB&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

