<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_update.proto

namespace GPBMetadata;

class FileUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBE\x02\x0A\x11file_update.proto\x12\x05proto\x1A\x0Ftimestamp.proto\x1A\x1Egoogle/protobuf/wrappers.proto\"\xC0\x01\x0A\x19FileUpdateTransactionBody\x12\x1D\x0A\x06fileID\x18\x01 \x01(\x0B2\x0D.proto.FileID\x12(\x0A\x0EexpirationTime\x18\x02 \x01(\x0B2\x10.proto.Timestamp\x12\x1C\x0A\x04keys\x18\x03 \x01(\x0B2\x0E.proto.KeyList\x12\x10\x0A\x08contents\x18\x04 \x01(\x0C\x12*\x0A\x04memo\x18\x05 \x01(\x0B2\x1C.google.protobuf.StringValueB&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

