<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_create.proto

namespace GPBMetadata;

class FileCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xCD\x02\x0A\x11file_create.proto\x12\x05proto\x1A\x0Ftimestamp.proto\"\xEF\x01\x0A\x19FileCreateTransactionBody\x12(\x0A\x0EexpirationTime\x18\x02 \x01(\x0B2\x10.proto.Timestamp\x12\x1C\x0A\x04keys\x18\x03 \x01(\x0B2\x0E.proto.KeyList\x12\x10\x0A\x08contents\x18\x04 \x01(\x0C\x12\x1F\x0A\x07shardID\x18\x05 \x01(\x0B2\x0E.proto.ShardID\x12\x1F\x0A\x07realmID\x18\x06 \x01(\x0B2\x0E.proto.RealmID\x12(\x0A\x10newRealmAdminKey\x18\x07 \x01(\x0B2\x0A.proto.KeyB\x02\x18\x01\x12\x0C\x0A\x04memo\x18\x08 \x01(\x09B&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

