<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: freeze_type.proto

namespace GPBMetadata;

class FreezeType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD5\x01\x0A\x11freeze_type.proto\x12\x05proto*\x88\x01\x0A\x0AFreezeType\x12\x17\x0A\x13UNKNOWN_FREEZE_TYPE\x10\x00\x12\x0F\x0A\x0BFREEZE_ONLY\x10\x01\x12\x13\x0A\x0FPREPARE_UPGRADE\x10\x02\x12\x12\x0A\x0EFREEZE_UPGRADE\x10\x03\x12\x10\x0A\x0CFREEZE_ABORT\x10\x04\x12\x15\x0A\x11TELEMETRY_UPGRADE\x10\x05B&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

