<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_by_key.proto

namespace GPBMetadata;

class GetByKey
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        \GPBMetadata\QueryHeader::initOnce();
        \GPBMetadata\ResponseHeader::initOnce();
        \GPBMetadata\CryptoAddLiveHash::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF5\x03\x0A\x10get_by_key.proto\x12\x05proto\x1A\x12query_header.proto\x1A\x15response_header.proto\x1A\x1Acrypto_add_live_hash.proto\"P\x0A\x0DGetByKeyQuery\x12\"\x0A\x06header\x18\x01 \x01(\x0B2\x12.proto.QueryHeader\x12\x17\x0A\x03key\x18\x02 \x01(\x0B2\x0A.proto.Key:\x02\x18\x01\"\xAE\x01\x0A\x08EntityID\x12%\x0A\x09accountID\x18\x01 \x01(\x0B2\x10.proto.AccountIDH\x00\x12#\x0A\x08liveHash\x18\x02 \x01(\x0B2\x0F.proto.LiveHashH\x00\x12\x1F\x0A\x06fileID\x18\x03 \x01(\x0B2\x0D.proto.FileIDH\x00\x12'\x0A\x0AcontractID\x18\x04 \x01(\x0B2\x11.proto.ContractIDH\x00:\x02\x18\x01B\x08\x0A\x06entity\"`\x0A\x10GetByKeyResponse\x12%\x0A\x06header\x18\x01 \x01(\x0B2\x15.proto.ResponseHeader\x12!\x0A\x08entities\x18\x02 \x03(\x0B2\x0F.proto.EntityID:\x02\x18\x01B&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

