<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule_create.proto

namespace GPBMetadata;

class ScheduleCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\SchedulableTransactionBody::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x84\x03\x0A\x15schedule_create.proto\x12\x05proto\x1A\x0Ftimestamp.proto\x1A\"schedulable_transaction_body.proto\"\xFE\x01\x0A\x1DScheduleCreateTransactionBody\x12C\x0A\x18scheduledTransactionBody\x18\x01 \x01(\x0B2!.proto.SchedulableTransactionBody\x12\x0C\x0A\x04memo\x18\x02 \x01(\x09\x12\x1C\x0A\x08adminKey\x18\x03 \x01(\x0B2\x0A.proto.Key\x12(\x0A\x0EpayerAccountID\x18\x04 \x01(\x0B2\x10.proto.AccountID\x12)\x0A\x0Fexpiration_time\x18\x05 \x01(\x0B2\x10.proto.Timestamp\x12\x17\x0A\x0Fwait_for_expiry\x18\x0D \x01(\x08B&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

