<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: throttle_definitions.proto

namespace GPBMetadata;

class ThrottleDefinitions
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD8\x02\x0A\x1Athrottle_definitions.proto\x12\x05proto\"W\x0A\x0DThrottleGroup\x12.\x0A\x0Aoperations\x18\x01 \x03(\x0E2\x1A.proto.HederaFunctionality\x12\x16\x0A\x0EmilliOpsPerSec\x18\x02 \x01(\x04\"c\x0A\x0EThrottleBucket\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x15\x0A\x0DburstPeriodMs\x18\x02 \x01(\x04\x12,\x0A\x0EthrottleGroups\x18\x03 \x03(\x0B2\x14.proto.ThrottleGroup\"E\x0A\x13ThrottleDefinitions\x12.\x0A\x0FthrottleBuckets\x18\x01 \x03(\x0B2\x15.proto.ThrottleBucketB&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

