<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: token_unfreeze_account.proto

namespace GPBMetadata;

class TokenUnfreezeAccount
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBE\x01\x0A\x1Ctoken_unfreeze_account.proto\x12\x05proto\"g\x0A#TokenUnfreezeAccountTransactionBody\x12\x1D\x0A\x05token\x18\x01 \x01(\x0B2\x0E.proto.TokenID\x12!\x0A\x07account\x18\x02 \x01(\x0B2\x10.proto.AccountIDB&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

