<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: token_claim_airdrop.proto

namespace GPBMetadata;

class TokenClaimAirdrop
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA9\x01\x0A\x19token_claim_airdrop.proto\x12\x05proto\"U\x0A TokenClaimAirdropTransactionBody\x121\x0A\x10pending_airdrops\x18\x01 \x03(\x0B2\x17.proto.PendingAirdropIdB&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

