<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: token_wipe_account.proto

namespace GPBMetadata;

class TokenWipeAccount
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDE\x01\x0A\x18token_wipe_account.proto\x12\x05proto\"\x8A\x01\x0A\x1FTokenWipeAccountTransactionBody\x12\x1D\x0A\x05token\x18\x01 \x01(\x0B2\x0E.proto.TokenID\x12!\x0A\x07account\x18\x02 \x01(\x0B2\x10.proto.AccountID\x12\x0E\x0A\x06amount\x18\x03 \x01(\x04\x12\x15\x0A\x0DserialNumbers\x18\x04 \x03(\x03B&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

