<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_contents.proto

namespace GPBMetadata;

class TransactionContents
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA0\x01\x0A\x1Atransaction_contents.proto\x12\x05proto\"K\x0A\x11SignedTransaction\x12\x11\x0A\x09bodyBytes\x18\x01 \x01(\x0C\x12#\x0A\x06sigMap\x18\x02 \x01(\x0B2\x13.proto.SignatureMapB&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

