<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_response.proto

namespace GPBMetadata;

class TransactionResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ResponseCode::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB6\x01\x0A\x1Atransaction_response.proto\x12\x05proto\"a\x0A\x13TransactionResponse\x12<\x0A\x1BnodeTransactionPrecheckCode\x18\x01 \x01(\x0E2\x17.proto.ResponseCodeEnum\x12\x0C\x0A\x04cost\x18\x02 \x01(\x04B&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

