<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: util_prng.proto

namespace GPBMetadata;

class UtilPrng
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Ar\x0A\x0Futil_prng.proto\x12\x05proto\"(\x0A\x17UtilPrngTransactionBody\x12\x0D\x0A\x05range\x18\x01 \x01(\x05B&\x0A\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

