<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: util_service.proto

namespace GPBMetadata;

class UtilService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\TransactionResponse::initOnce();
        \GPBMetadata\Transaction::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE7\x01\x0A\x12util_service.proto\x12\x05proto\x1A\x11transaction.proto2\x84\x01\x0A\x0BUtilService\x126\x0A\x04prng\x12\x12.proto.Transaction\x1A\x1A.proto.TransactionResponse\x12=\x0A\x0BatomicBatch\x12\x12.proto.Transaction\x1A\x1A.proto.TransactionResponseB(\x0A&com.hederahashgraph.service.proto.javab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

