<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state/history/history_types.proto

namespace Com\Hedera\Hapi\Node\State\History;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * A piece of new history in the form of an address book hash and
 * associated metadata.
 *
 * Generated from protobuf message <code>com.hedera.hapi.node.state.history.History</code>
 */
class History extends \Google\Protobuf\Internal\Message
{
    /**
     **
     * The address book hash of the new history.
     *
     * Generated from protobuf field <code>bytes address_book_hash = 1;</code>
     */
    protected $address_book_hash = '';
    /**
     **
     * The metadata associated to the address book.
     *
     * Generated from protobuf field <code>bytes metadata = 2;</code>
     */
    protected $metadata = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address_book_hash
     *          *
     *           The address book hash of the new history.
     *     @type string $metadata
     *          *
     *           The metadata associated to the address book.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\State\History\HistoryTypes::initOnce();
        parent::__construct($data);
    }

    /**
     **
     * The address book hash of the new history.
     *
     * Generated from protobuf field <code>bytes address_book_hash = 1;</code>
     * @return string
     */
    public function getAddressBookHash()
    {
        return $this->address_book_hash;
    }

    /**
     **
     * The address book hash of the new history.
     *
     * Generated from protobuf field <code>bytes address_book_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressBookHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->address_book_hash = $var;

        return $this;
    }

    /**
     **
     * The metadata associated to the address book.
     *
     * Generated from protobuf field <code>bytes metadata = 2;</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     **
     * The metadata associated to the address book.
     *
     * Generated from protobuf field <code>bytes metadata = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, False);
        $this->metadata = $var;

        return $this;
    }

}

